### PR TITLE
Feat/stellar contract

### PR DESCRIPTION
**Pull request by cryingraven**

### CODE REVIEW

**Review by lachlanglen — COMMENTED** [review]
Hey guys, just wanted to connect about the round factory pattern. I thought we had communicated that we wanted to manage all the rounds in a single contract to minimize round deployment cost.

What are your thoughts?

**Comment by cryingraven** [comment]
Hi, I have updated the latest source and merged the roundfactory in the round contract. I've tried it making a few rounds, it's also save up to 30 % when create new round from 1.5 XLM to 1 XLM.

**Review by lachlanglen — CHANGES_REQUESTED** [review]
Please check out [finished NEAR contract](https://github.com/PotLock/grantpicks/tree/feat/near-contract) and implement updates to Stellar contract to ensure cross-chain parity.

**Comment by cryingraven** [comment]
i have some update. i have finished almost all parities locally but the generated wasm (94 KB) is exceed from stellar wasm limit 64 KB.

**Comment by cryingraven** [comment]
I already fix size issue by remove external type and using single type. i will continue to refactor the code. according to your review and near contract

**Pull request merged**
